# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: Yjk5ZDhiMjY5ODBmM2ZiZTVjODM1MDI2OTQzMzQ5ZDliYzBiYWRhMzVlZDQ4ZmVlYTI1OGVmMDUwMTg1NTIyZGExOGYxNTM0OWVlNWQ4MGUzNWFhN2Q2MTQ3MmVkZGVkNjEyMmIyZmI0NjEwNGNlMDFiMWE3OWQ0ZjNhYzliZTM=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
